[font]
normal = { family = "Monaspace Xenon" }
bold = { family = "Monaspace Xenon", style = "Bold" }
italic = { family = "Monaspace Xenon", style = "Italic" }
bold_italic = { family = "Monaspace Xenon", style = "Bold Italic" }
size = 13.5
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true
