[font]
normal = { family = "Monaspace Radon", style = 'Medium' }
bold = { family = "Monaspace Radon", style = "Bold" }
italic = { family = "Monaspace Radon", style = "Italic" }
bold_italic = { family = "Monaspace Radon", style = "Bold Italic" }
size = 14
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true
