#!/usr/bin/env bash

RICE_NAME_FILE="$HOME/.config/bspwm/rice.cfg"
rofi_command="rofi -theme $HOME/.config/bspwm/selectors/RiceSelector.rasi"

# Options
meimei="♥ Meimei"

options="$meimei\n"
chosen="$(printf "$options" | $rofi_command -dmenu)"
	case $chosen in
			
			$meimei)
				cat <<< "meimei" > ${RICE_NAME_FILE}
				bspc wm -r
				;;

		esac
	
