#! /bin/sh
# bspwm configuration
# Author: aquapaka
# Email: aqua.tamlong@gmail.com

# ----- Variables ----- #
export RICE_NAME=$(<$HOME/.config/bspwm/rice.cfg)
POLY_DIR="$HOME/.config/bspwm/rices/$RICE_NAME/polybar"
export defnetif=$(ip route | grep '^default' | awk '{print $5}' | head -n1)

# ----- Functions ----- #
function launch() {
  local running
  running="$(pgrep -x "$1")"
  [ "$running" ] && kill -9 $(pgrep -x $1) 2> /dev/null
  eval "$* &"
}

function ReloadTerms() {
  cat $HOME/.config/bspwm/rices/$RICE_NAME/alacrittyrc > $HOME/.config/alacritty/alacritty.yml
}

function SetBspwmConf() {
	bspc config top_padding "$1"
	bspc config bottom_padding "$2"
    bspc config left_padding "$3"
	bspc config right_padding "$4"
	bspc config normal_border_color "$5" 
	bspc config active_border_color "$6"
	bspc config focused_border_color "$7"
	bspc config presel_feedback_color "$8"
}

# ----- Load Rice ----- #
case $RICE_NAME in
		meimei)
		  SetBspwmConf 0 0 0 0 "#1A1B26" "#9ece6a" "#0A9CF5" "#FBC02D"
		  launch polybar -q main -c ${POLY_DIR}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  ;;	  
	esac

# ----- Window rules ----- #
# remove all rules first
bspc rule -r *:*

# apps open in terminal [1] workspaces
bspc rule -a Alacritty desktop='^1' follow=on focus=on state=pseudo_tiled

# apps open in web [2] workspaces
bspc rule -a Google-chrome desktop='^2' follow=on focus=on

# apps open in files [3] workspaces
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a feh desktop='^3' follow=on focus=on state=floating

# apps open in code [4] workspaces
bspc rule -a Code desktop='^4' follow=on focus=on

# apps open in entertainment [5] workspaces
bspc rule -a Spotify desktop='^5' follow=on focus=on

# apps open in Communication [6] workspaces
bspc rule -a discord desktop='^6' follow=on focus=on
bspc rule -a TelegramDesktop desktop='^6' follow=on focus=on
bspc rule -a Caprine desktop='^6' follow=on focus=on

# apps open in settings [7] workspaces
bspc rule -a Xfce4-about desktop='^7' follow=on focus=on

# apps open in desktop [8] workspaces
bspc rule -a parsecd desktop='^8' follow=on focus=on

# External rules (Some app will required external rule)
bspc config external_rules_command $HOME/.config/bspwm/ExternalRules

# ----- Others BSPWM Configuration ----- #

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer         true

ReloadTerms
launch sxhkd
launch picom --config $HOME/.config/bspwm/rices/$RICE_NAME/picom.conf
~/.fehbg &
xinput --set-prop 'TPPS/2 IBM TrackPoint' 'libinput Accel Speed' 0
xsetroot -cursor_name left_ptr
