winget install Git -e;
winget install Alacritty -e;
winget install GlazeWM -e;
winget install --id Microsoft.PowerToys -e;
winget install --id Discord.Discord -e;
winget install --id Google.Chrome -e;
winget install --id Google.GoogleDrive -e;
winget install --id MSYS2.MSYS2 -e;
winget install --id Valve.Steam -e;
winget install "Lenovo Vantage";
winget install --id 7zip.7zip -e;
winget install --id VNGCorp.Zalo -e;
winget install --id CoreyButler.NVMforWindows -e;
winget install --id eza-community.eza -e;
winget install AnyDesk -e;
winget install -e --id Microsoft.VisualStudioCode -i --scope machine;
winget install Notion.Notion;
