winget install -e --id Microsoft.WindowsTerminal;
winget install -e --id Microsoft.PowerShell;
winget install -e --id twpayne.chezmoi;
winget install -e --id lars-berger.GlazeWM;
winget install -e --id Microsoft.PowerToys;
winget install -e -i --id Microsoft.VisualStudioCode;
winget install -e -i --id BlenderFoundation.Blender;
winget install -e --id Discord.Discord;
winget install -e --id Google.Chrome;
winget install -e --id Google.GoogleDrive;
winget install MSYS2.MSYS2;
winget install GodotEngine.GodotEngine;
winget install Postman.Postman;
winget install Valve.Steam;
winget install "Lenovo Vantage";
winget install 7zip.7zip;
winget install Zalo;
winget install OpenJS.NodeJS.LTS;
winget install eza;
winget install "Snipping Tool";
winget install anydesk;